export default [
  {
    canMove: true,
    canShot: true,
    canTarget: true,
    canMakeDroids: false,
    hp: 50,
    transformTime: 0,
  },
  {
    canMove: false,
    canShot: false,
    canTarget: false,
    canMakeDroids: true,
    hp: 200,
    transformTime: 8,
  },
  {
    canMove: false,
    canShot: true,
    canTarget: true,
    canMakeDroids: false,
    hp: 250,
    transformTime: 12,
  },
  {
    canMove: false,
    canShot: false,
    canTarget: false,
    canMakeDroids: false,
    hp: 200,
    transformTime: 16,
  },
  {
    canMove: false,
    canShot: false,
    canTarget: false,
    canMakeDroids: false,
    hp: 200,
  },
  {
    canMove: false,
    canShot: false,
    canTarget: false,
    canMakeDroids: false,
    canMine: false,
    hp: 5000,
  },
  {
    canMove: true,
    canShot: true,
    canTarget: true,
    canMakeDroids: false,
    canMine: true,
    hp: 1000,
  },
];
